### ISSUE TITLE
Visit Stuck on OUTCOME_FOR_DELIVERED_SERVICE_NEEDED

### ISSUE THREAD

**Issue by fredovecino** [qmatic/orchestra-counter#3]
Hello there,

Sometimes we are not able to end visits because it is stuck on a state of OUTCOME_FOR_DELIVERED_SERVICE_NEEDED even though it does have outcomes.

We can replicate the issue by doing the following:
1. Call a visit
2. Add a delivered service that needs an outcome
3. Delete that delivered service without choosing an outcome
4. Now the visit can't be ended

We also made a [video showing the behaviur](https://youtu.be/Vq4pzKkXxLY).

**Comment by jesrus** [comment]
Hi,

What version of the webapp are you testing.
I tried to reproduce the issue following the steps in the video but could not reproduce the issue.

In order to get attention to this I suggest you raise a support case with the following information

1. Version of Orchestra
2.  Version of the Counter webapp and utts
3. Exact steps to reproduce the issue

log files if relevant.

Regards Jessica

**Comment by fredovecino** [comment]
Hi Jessica,
Apparently this issue is fixed in Orchestra Update 9 release, it only occurs on previous versions. And it doesn´t seem to be caused by the Counter webapp.
Thanks!

**Comment by jesrus** [comment]
OK good
